### ISSUE TITLE
Index using Quads

### ISSUE THREAD

**Issue by tpluscode** [rdfjs-base/term-map#3]
It appears that it is not possible to use RDF/JS `Quad` as map key but it should be possible given RDF* where Quad is a subtype of Term

The exact problem is that `termToNTriples` from `@rdfjs/to-ntriples` returns `undefined` for a quad parameter. This is probably correct, especially that there is also an export `quadToNTriples`.

I propose to check the the `get/set/has/delete` argument and call the other function if it is a quad

**Comment by bergos** [comment]
fixed in latest release.
